language: generic
sudo: required
# Hey Travis, we need a copy of docker ready to go!
services:
   - docker

before_install:
   - docker build -t mgarciac88/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true mgarciac88/docker-react npm run test
