language: generic
sudo: required
# Hey Travis, we need a copy of docker ready to go!
services:
   - docker

before_install:
   - docker build -t mgarciac88/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true mgarciac88/docker-react npm run test

deploy:
   provider: elasticbeanstalk
   region: 'us-east-1'
   app: 'docker-react'
   env: 'DockerReact-env'
   bucket_name: 'elasticbeanstalk-us-east-1-626040936436'
   bucket_path: 'docker-react'
   on:
      branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
